### ISSUE TITLE
Docker image failing to run

### ISSUE THREAD

**Issue by nearcatch** [jslay88/qbt_migrate#16]
Can't even print the help message:

```bash
root@server:/mnt/user/appdata/docker# docker run -v BT_backup:/tmp/BT_Backup jslay88/qbt_migrate -h
Existing Path: Traceback (most recent call last):
  File "/usr/local/bin/qbt_migrate", line 33, in <module>
    sys.exit(load_entry_point('qbt-migrate', 'console_scripts', 'qbt_migrate')())
  File "/opt/qbt_migrate/qbt_migrate/cli.py", line 44, in main
    args.existing_path = input('Existing Path: ')
EOFError: EOF when reading a line
```

**Comment by jslay88** [comment]
#18 resolves
