### ISSUE TITLE
Error while trying to change drive letter

### ISSUE THREAD

**Issue by MrDemous** [jslay88/qbt_migrate#6]
I'm getting this error when I try to change a drive letter from H:\ to G:\

I'm using Windows 10 64bit and Python 3.8.3

> Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\bencode\__init__.py", line 180, in bdecode
    r, l = decode_func[value[0:1]](value, 0)
KeyError: b'\x08'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "cli.py", line 49, in <module>
    qbm.run(args.existing_path, args.new_path, args.target_os)
  File "C:\qbt\qbt_migrate\classes.py", line 45, in run
    for fast_resume in self.discover_relevant_fast_resume(self.bt_backup_path, existing_path):
  File "C:\qbt\qbt_migrate\classes.py", line 63, in discover_relevant_fast_resume
    fast_resume = FastResume(os.path.join(bt_backup_path, file))
  File "C:\qbt\qbt_migrate\classes.py", line 95, in __init__
    self._data = bencode.bread(self.file_path)
  File "C:\Python38\lib\site-packages\bencode\__init__.py", line 325, in bread
    return bdecode(fd.read())
  File "C:\Python38\lib\site-packages\bencode\__init__.py", line 182, in bdecode
    raise BencodeDecodeError("not a valid bencoded string")
bencode.exceptions.BencodeDecodeError: not a valid bencoded string

**Comment by jslay88** [comment]
Please provide a test fast resume file That causes the issue and the
arguments you are using when running the script.

**Comment by MrDemous** [comment]
Apparently there were some corrupted fastresume files in my BT_backup folder, I removed them and the script works just fine now.

Thanks @jslay88

**Comment by jslay88** [comment]
Glad you got the issue solved. 👍
