### ISSUE TITLE
Docker fails

### ISSUE THREAD

**Issue by bug-re-port-er** [jslay88/qbt_migrate#69]
After running:

`docker run -v %LOCALAPPDATA%/qBittorrent/BT_backup:/tmp/BT_backup jslay88/qbt_migrate -e G:\ -n T:\`

I get an error:
```
Existing and New paths are regex patterns (capture groups recommended)? [y/N]: Traceback (most recent call last):
  File "/usr/local/bin/qbt_migrate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qbt_migrate/cli.py", line 106, in main
    answer := input(
              ^^^^^^
EOFError: EOF when reading a line
```

**Comment by PLP-GTR** [comment]
Include the `-i` flag to have interactive shell in docker:

`docker run -i -v %LOCALAPPDATA%/qBittorrent/BT_backup:/tmp/BT_backup jslay88/qbt_migrate -e G:\ -n T:\`
