### ISSUE TITLE
Unable to parse

### ISSUE THREAD

**Issue by ialima** [jslay88/qbt_migrate#73]
Hi.

It is showing these errors, any suggestions?
```

PS C:\Users\ialim> qbt_migrate -e S:\ -n X:\ -t Windows
BT_backup Path C:\Users\ialim\AppData\Local\qBittorrent\BT_backup:
Existing and New paths are regex patterns (capture groups recommended)? [y/N]: n
🗄️ Creating Archive C:\Users\ialim\AppData\Local\qBittorrent\BT_backup\fastresume_backup20241230223142.zip ...
✔️ Done!
🕵️ Searching for .fastresume files with path S:\ ...
🛑 Unable to parse C:\Users\ialim\AppData\Local\qBittorrent\BT_backup\0a58a73d53130c2246af5da6678ecfa0570de110.fastresume. Stopping Discovery!
Traceback (most recent call last):
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\bencodepy\decoder.py", line 85, in decode
    data, length = self.decode_func[value[0:1]](value, 0)
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: b'\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Scripts\qbt_migrate.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\qbt_migrate\cli.py", line 130, in main
    qbm.run(args.existing_path, args.new_path, args.regex, args.target_os, True, args.skip_bad_files)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\qbt_migrate\classes.py", line 61, in run
    for fast_resume in self.discover_relevant_fast_resume(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.bt_backup_path, existing_path, regex_path, not skip_bad_files
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\qbt_migrate\classes.py", line 99, in discover_relevant_fast_resume
    raise e
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\qbt_migrate\classes.py", line 95, in discover_relevant_fast_resume
    fast_resume = FastResume(bt_backup_path / file)
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\qbt_migrate\classes.py", line 146, in __init__
    self._data = bencode.read(self.file_path)
                 ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\bencodepy\__init__.py", line 102, in read
    return self.decode(fd.read())
           ~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\bencodepy\__init__.py", line 72, in decode
    return self.decoder.decode(value)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\ialim\AppData\Local\Programs\Python\Python313\Lib\site-packages\bencodepy\decoder.py", line 87, in decode
    raise BencodeDecodeError("not a valid bencoded string")
bencodepy.exceptions.BencodeDecodeError: not a valid bencoded string
```

**Comment by jslay88** [comment]
Looks like you have a corrupt fastresume file. You can try and give me this file to manually inspect (note it may contain sensitive information), delete this file, or use the skip bad files options. 

Problem file C:\Users\ialim\AppData\Local\qBittorrent\BT_backup\0a58a73d53130c2246af5da6678ecfa0570de110.fastresume

**Comment by ialima** [comment]
Hi friend, thank you very much for replying.

I hadn't seen the option to skip bad files, sorry.

I ended up changing the folder using qBit's own native option, thank goodness it only asks once, I was wondering if this is new.

But when I need it I will test your application again. Thank you for your dedication.
